// Generado por tools/fetch_images.py — imágenes de AniList.
window.CHAR_IMAGES = {
"aot:Annie Leonhart": "https://s4.anilist.co/file/anilistcdn/character/large/b46490-tan274Ifc1Jf.jpg",
"aot:Armin Arlert": "https://s4.anilist.co/file/anilistcdn/character/large/b46494-g7xYYuBtYPnO.png",
"aot:Bertholdt Hoover": "https://s4.anilist.co/file/anilistcdn/character/large/b46488-wm6HvkdkHoZu.jpg",
"aot:Eren Jaeger": "https://s4.anilist.co/file/anilistcdn/character/large/b40882-dsj7IP943WFF.jpg",
"aot:Erwin Smith": "https://s4.anilist.co/file/anilistcdn/character/large/b46496-Mu86MENd5wNB.png",
"aot:Hange Zoe": "https://s4.anilist.co/file/anilistcdn/character/large/b71121-7R7CnQd3lHgt.png",
"aot:Hannes": "https://s4.anilist.co/file/anilistcdn/character/large/b46492-5kRaMLDCVD0B.jpg",
"aot:Historia Reiss": "https://s4.anilist.co/file/anilistcdn/character/large/b62481-ZZDa7vn17lMU.png",
"aot:Jean Kirstein": "https://s4.anilist.co/file/anilistcdn/character/large/b46498-ritqAj9FW6jX.png",
"aot:Levi Ackerman": "https://s4.anilist.co/file/anilistcdn/character/large/b45627-CR68RyZmddGG.png",
"aot:Mikasa Ackerman": "https://s4.anilist.co/file/anilistcdn/character/large/b40881-F3gr1PkreDvj.png",
"aot:Reiner Braun": "https://s4.anilist.co/file/anilistcdn/character/large/b46484-P6A2GjNQn49F.png",
"aot:Sasha Blouse": "https://s4.anilist.co/file/anilistcdn/character/large/b45887-QPtJH0KwqthW.jpg",
"aot:Ymir": "https://s4.anilist.co/file/anilistcdn/character/large/b71479-huCD908XIdqv.png",
"aot:Zeke Jaeger": "https://s4.anilist.co/file/anilistcdn/character/large/b125661-FiqFvAtNlL0v.png",
"bc:Asta": "https://s4.anilist.co/file/anilistcdn/character/large/b123285-tKijiuQErDS0.png",
"bc:Fuegoleon Vermillion": "https://s4.anilist.co/file/anilistcdn/character/large/b124521-MqX5KT2tGSa8.png",
"bc:Julius Novachrono": "https://s4.anilist.co/file/anilistcdn/character/large/b124435-gXFVXWrCcieK.jpg",
"bc:Mereoleona Vermillion": "https://s4.anilist.co/file/anilistcdn/character/large/b124522-lJK4Hy6Aokie.png",
"bc:Noelle Silva": "https://s4.anilist.co/file/anilistcdn/character/large/b123283-7nJHtKha0LSm.png",
"bc:Yami Sukehiro": "https://s4.anilist.co/file/anilistcdn/character/large/b124440-Lpdo6y8cljV6.png",
"bc:Yuno": "https://s4.anilist.co/file/anilistcdn/character/large/b123284-w6kIFYnTclMd.png",
"bebop:Ed": "https://s4.anilist.co/file/anilistcdn/character/large/b16-80wd87nl1Rue.png",
"bebop:Faye Valentine": "https://s4.anilist.co/file/anilistcdn/character/large/b2-0Iszg6Izgt4p.png",
"bebop:Jet Black": "https://s4.anilist.co/file/anilistcdn/character/large/b3-JjH9Si9UM1NZ.png",
"bebop:Spike Spiegel": "https://s4.anilist.co/file/anilistcdn/character/large/b1-ChxaldmieFlQ.png",
"bebop:Vicious": "https://s4.anilist.co/file/anilistcdn/character/large/b2734-aglO8RKNVxnn.jpg",
"bleach:Byakuya Kuchiki": "https://s4.anilist.co/file/anilistcdn/character/large/b907-kgnDKeMtEN5y.png",
"bleach:Genryusai Yamamoto": "https://s4.anilist.co/file/anilistcdn/character/large/b5726-mO7kc8Abka9J.jpg",
"bleach:Gin Ichimaru": "https://s4.anilist.co/file/anilistcdn/character/large/b1087-wMTny26FezYB.png",
"bleach:Grimmjow Jaegerjaquez": "https://s4.anilist.co/file/anilistcdn/character/large/b1080-JUNo2Or0UGZg.jpg",
"bleach:Ichigo Kurosaki": "https://s4.anilist.co/file/anilistcdn/character/large/b5-a7bkJgjhhigE.png",
"bleach:Kenpachi Zaraki": "https://s4.anilist.co/file/anilistcdn/character/large/b909-slhoFBon7oiH.jpg",
"bleach:Kisuke Urahara": "https://s4.anilist.co/file/anilistcdn/character/large/b210-mw01NrQfRjzT.png",
"bleach:Orihime Inoue": "https://s4.anilist.co/file/anilistcdn/character/large/b7-JdR4betokDjR.jpg",
"bleach:Renji Abarai": "https://s4.anilist.co/file/anilistcdn/character/large/b906-ImRjx5HFM8X6.png",
"bleach:Rukia Kuchiki": "https://s4.anilist.co/file/anilistcdn/character/large/b6-25WoBeWMZXBc.png",
"bleach:Shunsui Kyoraku": "https://s4.anilist.co/file/anilistcdn/character/large/b1088-6oO10CmxZ1lP.jpg",
"bleach:Sosuke Aizen": "https://s4.anilist.co/file/anilistcdn/character/large/b1086-qR9218BjZTC0.png",
"bleach:Toshiro Hitsugaya": "https://s4.anilist.co/file/anilistcdn/character/large/b245-buy3Cfn6IFSB.jpg",
"bleach:Ulquiorra Cifer": "https://s4.anilist.co/file/anilistcdn/character/large/b1081-xLTqHfLL2I2W.png",
"bleach:Uryu Ishida": "https://s4.anilist.co/file/anilistcdn/character/large/b564-a6LJitrjSfKC.jpg",
"bleach:Yasutora Sado": "https://s4.anilist.co/file/anilistcdn/character/large/575.jpg",
"bleach:Yhwach": "https://s4.anilist.co/file/anilistcdn/character/large/b68537-1bRB5OdseCp0.jpg",
"bleach:Yoruichi Shihoin": "https://s4.anilist.co/file/anilistcdn/character/large/b908-JSYUkJLCw1f0.png",
"bluelock:Hyoma Chigiri": "https://s4.anilist.co/file/anilistcdn/character/large/b167444-JTHkkJAX4E3q.png",
"bluelock:Jinpachi Ego": "https://s4.anilist.co/file/anilistcdn/character/large/b140857-DOTyKBCufon9.png",
"bluelock:Meguru Bachira": "https://s4.anilist.co/file/anilistcdn/character/large/b162213-4czykzdxmWG6.png",
"bluelock:Reo Mikage": "https://s4.anilist.co/file/anilistcdn/character/large/b169394-8KDqHUN1VyGC.png",
"bluelock:Rin Itoshi": "https://s4.anilist.co/file/anilistcdn/character/large/b169395-oYTkJnimI3Eu.png",
"bluelock:Seishiro Nagi": "https://s4.anilist.co/file/anilistcdn/character/large/b162969-WGnGyVQrFi0X.png",
"bluelock:Shoei Barou": "https://s4.anilist.co/file/anilistcdn/character/large/b169401-jeepvEsqW4Ns.png",
"bluelock:Yoichi Isagi": "https://s4.anilist.co/file/anilistcdn/character/large/b140856-wVzKSyvU7R5B.png",
"cg:C.C.": "https://s4.anilist.co/file/anilistcdn/character/large/b1111-UhmlFtRFrnWa.png",
"cg:Charles zi Britannia": "https://s4.anilist.co/file/anilistcdn/character/large/b5610-TuH7RZiCqQBd.png",
"cg:Kallen Kozuki": "https://s4.anilist.co/file/anilistcdn/character/large/b558-8tSMZ4a0LWrn.jpg",
"cg:Lelouch Lamperouge": "https://s4.anilist.co/file/anilistcdn/character/large/b417-gVLmIJu9phcK.png",
"cg:Nunnally vi Britannia": "https://s4.anilist.co/file/anilistcdn/character/large/b1110-TSlN2WkhDJ1T.png",
"cg:Schneizel el Britannia": "https://s4.anilist.co/file/anilistcdn/character/large/b1710-GA8qDtSsY4jN.png",
"cg:Suzaku Kururugi": "https://s4.anilist.co/file/anilistcdn/character/large/b559-KRvTdc6zdCuU.jpg",
"csm:Aki Hayakawa": "https://s4.anilist.co/file/anilistcdn/character/large/b137081-TSrUR3mUJL6r.png",
"csm:Angel Devil": "https://s4.anilist.co/file/anilistcdn/character/large/b152231-jiMRx9je7H6y.png",
"csm:Denji": "https://s4.anilist.co/file/anilistcdn/character/large/b130102-FO1VHNnEnLlB.png",
"csm:Himeno": "https://s4.anilist.co/file/anilistcdn/character/large/b144596-kvL6SD2litJu.png",
"csm:Kishibe": "https://s4.anilist.co/file/anilistcdn/character/large/b144593-hdCTT9t54z0s.png",
"csm:Kobeni Higashiyama": "https://s4.anilist.co/file/anilistcdn/character/large/b144594-0dbO1NSYeZ12.png",
"csm:Makima": "https://s4.anilist.co/file/anilistcdn/character/large/b137080-UHcynYNjb5ZU.png",
"csm:Pochita": "https://s4.anilist.co/file/anilistcdn/character/large/b170266-bBXPkNJnd3mg.png",
"csm:Power": "https://s4.anilist.co/file/anilistcdn/character/large/b137079-6yLEUYR3bmpr.png",
"csm:Reze": "https://s4.anilist.co/file/anilistcdn/character/large/b148740-ceAibPxLW8rR.png",
"dandadan:Aira Shiratori": "https://s4.anilist.co/file/anilistcdn/character/large/b245466-rd5I5mchZ3bv.png",
"dandadan:Momo Ayase": "https://s4.anilist.co/file/anilistcdn/character/large/b222594-24Jn7qlI5spH.png",
"dandadan:Okarun": "https://s4.anilist.co/file/anilistcdn/character/large/b222593-qBqUvpodooAI.png",
"dandadan:Seiko Ayase": "https://s4.anilist.co/file/anilistcdn/character/large/b234824-i3s64ueaBqGq.png",
"dandadan:Turbo Granny": "https://s4.anilist.co/file/anilistcdn/character/large/b239956-Fok0Pl3rNOEL.png",
"deathnote:L": "https://s4.anilist.co/file/anilistcdn/character/large/b71-1W4panC53vfs.png",
"deathnote:Light Yagami": "https://s4.anilist.co/file/anilistcdn/character/large/b80-26EhwSsSqQ50.png",
"deathnote:Mello": "https://s4.anilist.co/file/anilistcdn/character/large/b463-QBLeLf6XxVg6.png",
"deathnote:Misa Amane": "https://s4.anilist.co/file/anilistcdn/character/large/b835-CiZa8y2z2gCz.png",
"deathnote:Near": "https://s4.anilist.co/file/anilistcdn/character/large/n464-6KeJpU6g7Hwj.jpg",
"deathnote:Rem": "https://s4.anilist.co/file/anilistcdn/character/large/n1905-9GfCvLFKNRLR.png",
"deathnote:Ryuk": "https://s4.anilist.co/file/anilistcdn/character/large/b75-IkEpzO21LgFy.jpg",
"deathnote:Teru Mikami": "https://s4.anilist.co/file/anilistcdn/character/large/n1904-xKw2NgiE6VbU.jpg",
"dragonball:Androide 18": "https://s4.anilist.co/file/anilistcdn/character/large/b4318-HfIy9rOIOZXM.png",
"dragonball:Bills": "https://s4.anilist.co/file/anilistcdn/character/large/b76348-pGWrznfxgPIV.png",
"dragonball:Broly": "https://s4.anilist.co/file/anilistcdn/character/large/b4945-iE59qIP7TxPu.png",
"dragonball:Bulma": "https://s4.anilist.co/file/anilistcdn/character/large/b678-2YCe13F0tFos.jpg",
"dragonball:Cell": "https://s4.anilist.co/file/anilistcdn/character/large/3908.jpg",
"dragonball:Chi-Chi": "https://s4.anilist.co/file/anilistcdn/character/large/2102.jpg",
"dragonball:Freezer": "https://s4.anilist.co/file/anilistcdn/character/large/b3694-bDfOdSSdFfPv.png",
"dragonball:Goku Black": "https://s4.anilist.co/file/anilistcdn/character/large/b126199-SKYF7o73fQtX.jpg",
"dragonball:Krillin": "https://s4.anilist.co/file/anilistcdn/character/large/b2159-qtEuMYyOUkwY.jpg",
"dragonball:Maestro Roshi": "https://s4.anilist.co/file/anilistcdn/character/large/b6167-aMPt1bHf5YbV.jpg",
"dragonball:Majin Buu": "https://s4.anilist.co/file/anilistcdn/character/large/1012.jpg",
"dragonball:Piccolo": "https://s4.anilist.co/file/anilistcdn/character/large/b914-KuS8AWjqBrqa.jpg",
"dragonball:Raditz": "https://s4.anilist.co/file/anilistcdn/character/large/6155.jpg",
"dragonball:Son Gohan": "https://s4.anilist.co/file/anilistcdn/character/large/b2093-kdFZhqcNSsqW.png",
"dragonball:Son Goku": "https://s4.anilist.co/file/anilistcdn/character/large/246-wsRRr6z1kii8.png",
"dragonball:Tenshinhan": "https://s4.anilist.co/file/anilistcdn/character/large/b5499-Cn9kTD2J9dU5.png",
"dragonball:Trunks": "https://s4.anilist.co/file/anilistcdn/character/large/b2707-YKWmn4q87oF8.png",
"dragonball:Vegeta": "https://s4.anilist.co/file/anilistcdn/character/large/b913-NIFkKazWM8VO.png",
"dragonball:Whis": "https://s4.anilist.co/file/anilistcdn/character/large/b76346-BNh2DE5Rh2IW.jpg",
"dragonball:Yamcha": "https://s4.anilist.co/file/anilistcdn/character/large/b4014-of2ONLvA7T8p.jpg",
"eva:Asuka Langley Soryu": "https://s4.anilist.co/file/anilistcdn/character/large/b94-d631a3Z2KPvd.png",
"eva:Gendo Ikari": "https://s4.anilist.co/file/anilistcdn/character/large/b1257-qByikcrE8KTG.png",
"eva:Kaworu Nagisa": "https://s4.anilist.co/file/anilistcdn/character/large/b1261-HYRv3HpsSL92.jpg",
"eva:Misato Katsuragi": "https://s4.anilist.co/file/anilistcdn/character/large/b1259-afTQkZ5SVMOn.png",
"eva:Rei Ayanami": "https://s4.anilist.co/file/anilistcdn/character/large/86-cA1zL7fyls8E.jpg",
"eva:Shinji Ikari": "https://s4.anilist.co/file/anilistcdn/character/large/b89-ZtZhXkh1rITn.png",
"fma:Alex Louis Armstrong": "https://s4.anilist.co/file/anilistcdn/character/large/b2079-RnhPS44vyqpJ.jpg",
"fma:Alphonse Elric": "https://s4.anilist.co/file/anilistcdn/character/large/b12-tCKu8yK5kFL5.jpg",
"fma:Edward Elric": "https://s4.anilist.co/file/anilistcdn/character/large/b11-TA5Nuk7EDUZG.jpg",
"fma:Envy": "https://s4.anilist.co/file/anilistcdn/character/large/b651-S4mzVOTMzej6.png",
"fma:Greed": "https://s4.anilist.co/file/anilistcdn/character/large/b351-XMQzTuMy2Xtn.jpg",
"fma:Izumi Curtis": "https://s4.anilist.co/file/anilistcdn/character/large/b67-ggB3aC6DzQqB.png",
"fma:King Bradley": "https://s4.anilist.co/file/anilistcdn/character/large/b5103-jnflrjKevO3z.png",
"fma:Lust": "https://s4.anilist.co/file/anilistcdn/character/large/b650-viEy6bOIcGiU.png",
"fma:Maes Hughes": "https://s4.anilist.co/file/anilistcdn/character/large/b69-MRetSG8Qevvu.png",
"fma:Olivier Mira Armstrong": "https://s4.anilist.co/file/anilistcdn/character/large/n3934-MKTV6tQeP8T3.png",
"fma:Riza Hawkeye": "https://s4.anilist.co/file/anilistcdn/character/large/b70-k4bCgDspyOdI.png",
"fma:Roy Mustang": "https://s4.anilist.co/file/anilistcdn/character/large/b68-moBLY2WO2am3.png",
"fma:Scar": "https://s4.anilist.co/file/anilistcdn/character/large/b66-bLbGWXrmDqfV.png",
"fma:Van Hohenheim": "https://s4.anilist.co/file/anilistcdn/character/large/b9792-YA8kiO4NjmGL.jpg",
"fma:Winry Rockbell": "https://s4.anilist.co/file/anilistcdn/character/large/63-xloedtYxiJ2E.jpg",
"frieren:Aura": "https://s4.anilist.co/file/anilistcdn/character/large/b219110-LEB5T4oG0gel.png",
"frieren:Eisen": "https://s4.anilist.co/file/anilistcdn/character/large/b184312-kxd5H6iOHIq4.png",
"frieren:Fern": "https://s4.anilist.co/file/anilistcdn/character/large/b183965-uGFohBjlFoTp.png",
"frieren:Flamme": "https://s4.anilist.co/file/anilistcdn/character/large/b219733-FgXseEhMdDE9.png",
"frieren:Frieren": "https://s4.anilist.co/file/anilistcdn/character/large/b176754-PCnpqIOkjhFk.png",
"frieren:Heiter": "https://s4.anilist.co/file/anilistcdn/character/large/b184310-tiXvrq4FINXP.jpg",
"frieren:Himmel": "https://s4.anilist.co/file/anilistcdn/character/large/b184311-wQFySqYXEqf1.png",
"frieren:Stark": "https://s4.anilist.co/file/anilistcdn/character/large/b184313-CQl6GSt4RSny.jpg",
"frieren:Ubel": "https://s4.anilist.co/file/anilistcdn/character/large/b246057-ixvDfpng6I1S.png",
"ft:Erza Scarlet": "https://s4.anilist.co/file/anilistcdn/character/large/b5189-GR1xdok9SFsN.jpg",
"ft:Gajeel Redfox": "https://s4.anilist.co/file/anilistcdn/character/large/b16893-l9HhHQ8j09H5.jpg",
"ft:Gray Fullbuster": "https://s4.anilist.co/file/anilistcdn/character/large/b4839-p2SBgjdTxHxk.png",
"ft:Happy": "https://s4.anilist.co/file/anilistcdn/character/large/b5188-1jTaic3aJ7Ds.jpg",
"ft:Juvia Lockser": "https://s4.anilist.co/file/anilistcdn/character/large/b9719-xh4xqTV6byNl.png",
"ft:Laxus Dreyar": "https://s4.anilist.co/file/anilistcdn/character/large/b8294-24LS3f4VMrfs.jpg",
"ft:Lucy Heartfilia": "https://s4.anilist.co/file/anilistcdn/character/large/b5186-izgXf2S86K9u.png",
"ft:Makarov Dreyar": "https://s4.anilist.co/file/anilistcdn/character/large/5333.jpg",
"ft:Mirajane Strauss": "https://s4.anilist.co/file/anilistcdn/character/large/b5190-Xql1rGKUv1ql.png",
"ft:Natsu Dragneel": "https://s4.anilist.co/file/anilistcdn/character/large/b5187-y1OEdRu9sPN2.png",
"ft:Wendy Marvell": "https://s4.anilist.co/file/anilistcdn/character/large/b28886-unO1rEi3zdyF.jpg",
"ft:Zeref Dragneel": "https://s4.anilist.co/file/anilistcdn/character/large/37720-WfpaYoeW2OkV.jpg",
"haikyuu:Daichi Sawamura": "https://s4.anilist.co/file/anilistcdn/character/large/b67323-yFbLDAfJ5ysG.png",
"haikyuu:Kei Tsukishima": "https://s4.anilist.co/file/anilistcdn/character/large/b67329-k7mDdqQ6rJ4w.png",
"haikyuu:Kenma Kozume": "https://s4.anilist.co/file/anilistcdn/character/large/b71267-q44J2MXMinXD.jpg",
"haikyuu:Koshi Sugawara": "https://s4.anilist.co/file/anilistcdn/character/large/b67321-cxP7NdI0JC3H.png",
"haikyuu:Kotaro Bokuto": "https://s4.anilist.co/file/anilistcdn/character/large/b88937-2GSqkX9TIzYy.png",
"haikyuu:Shoyo Hinata": "https://s4.anilist.co/file/anilistcdn/character/large/b64769-WoWlCMLLgJ14.png",
"haikyuu:Tetsuro Kuroo": "https://s4.anilist.co/file/anilistcdn/character/large/b71269-pi9vjyxKPFAu.jpg",
"haikyuu:Tobio Kageyama": "https://s4.anilist.co/file/anilistcdn/character/large/b64771-BuCVs7B8bBdh.png",
"haikyuu:Toru Oikawa": "https://s4.anilist.co/file/anilistcdn/character/large/b71611-cUZwVfzeNXD9.png",
"haikyuu:Yu Nishinoya": "https://s4.anilist.co/file/anilistcdn/character/large/b67327-zQb1dlC7joPb.jpg",
"hxh:Biscuit Krueger": "https://s4.anilist.co/file/anilistcdn/character/large/b13898-nHq3fRmp9uPD.png",
"hxh:Chrollo Lucilfer": "https://s4.anilist.co/file/anilistcdn/character/large/b58-USOmsz3nursi.jpg",
"hxh:Gon Freecss": "https://s4.anilist.co/file/anilistcdn/character/large/b30-lyFExKyDhefc.jpg",
"hxh:Hisoka Morow": "https://s4.anilist.co/file/anilistcdn/character/large/b31-FZckOuu7L1un.png",
"hxh:Illumi Zoldyck": "https://s4.anilist.co/file/anilistcdn/character/large/b57-pTFguojSOQZW.png",
"hxh:Isaac Netero": "https://s4.anilist.co/file/anilistcdn/character/large/b14489-WgGsdlQJka65.jpg",
"hxh:Killua Zoldyck": "https://s4.anilist.co/file/anilistcdn/character/large/b27-Z5O02kQUydpT.jpg",
"hxh:Kite": "https://s4.anilist.co/file/anilistcdn/character/large/b20594-QQJBR3LYobbv.jpg",
"hxh:Kurapika": "https://s4.anilist.co/file/anilistcdn/character/large/b28-ivA7UGnfE40a.png",
"hxh:Leorio Paradinight": "https://s4.anilist.co/file/anilistcdn/character/large/b29-RgzoSeKmDYzl.jpg",
"hxh:Meruem": "https://s4.anilist.co/file/anilistcdn/character/large/b23277-EYmIxzL64Mji.png",
"hxh:Neferpitou": "https://s4.anilist.co/file/anilistcdn/character/large/b12300-kYzopQUTLa9A.png",
"hxh:Uvogin": "https://s4.anilist.co/file/anilistcdn/character/large/5836.jpg",
"hxh:Wing": "https://s4.anilist.co/file/anilistcdn/character/large/b22521-lW31xQRGKQm8.jpg",
"jjk:Aoi Todo": "https://s4.anilist.co/file/anilistcdn/character/large/b137975-6TH7PiLWJaqy.png",
"jjk:Choso": "https://s4.anilist.co/file/anilistcdn/character/large/b157116-2jYQf3y8NeTZ.png",
"jjk:Jogo": "https://s4.anilist.co/file/anilistcdn/character/large/b156991-niYjdp9CxO4w.png",
"jjk:Kento Nanami": "https://s4.anilist.co/file/anilistcdn/character/large/b133704-8wLTGjc234q2.png",
"jjk:Mahito": "https://s4.anilist.co/file/anilistcdn/character/large/b133702-Y7JRG5vAvjIL.png",
"jjk:Maki Zenin": "https://s4.anilist.co/file/anilistcdn/character/large/b134167-5TCytk45YByD.png",
"jjk:Megumi Fushiguro": "https://s4.anilist.co/file/anilistcdn/character/large/b126635-L0y3I92JSUkN.png",
"jjk:Nobara Kugisaki": "https://s4.anilist.co/file/anilistcdn/character/large/b133700-f6sOO3TcgLV6.png",
"jjk:Panda": "https://s4.anilist.co/file/anilistcdn/character/large/b137974-9qnK3DPrvLKh.jpg",
"jjk:Ryomen Sukuna": "https://s4.anilist.co/file/anilistcdn/character/large/b133701-rCQuDpHr3UZL.png",
"jjk:Satoru Gojo": "https://s4.anilist.co/file/anilistcdn/character/large/b127691-9zqh1xpIubn7.png",
"jjk:Suguru Geto": "https://s4.anilist.co/file/anilistcdn/character/large/b133699-FCnXaISgazAi.png",
"jjk:Toge Inumaki": "https://s4.anilist.co/file/anilistcdn/character/large/b157115-kdhRYQdVhH95.png",
"jjk:Toji Fushiguro": "https://s4.anilist.co/file/anilistcdn/character/large/b162722-btzdghBizxKS.jpg",
"jjk:Yoshinobu Gakuganji": "https://s4.anilist.co/file/anilistcdn/character/large/b157867-dHdd8ZECuzHx.png",
"jjk:Yuji Itadori": "https://s4.anilist.co/file/anilistcdn/character/large/b127212-FVm2tD0erQ5B.png",
"jjk:Yuta Okkotsu": "https://s4.anilist.co/file/anilistcdn/character/large/b129571-GHJk7gviHOOw.jpg",
"jojo:Bruno Bucciarati": "https://s4.anilist.co/file/anilistcdn/character/large/b13045-TIpIF82cMkG9.png",
"jojo:Dio Brando": "https://s4.anilist.co/file/anilistcdn/character/large/b4004-w0OtWuvjhftG.png",
"jojo:Giorno Giovanna": "https://s4.anilist.co/file/anilistcdn/character/large/b10529-AloL8jjZwjsg.png",
"jojo:Jean Pierre Polnareff": "https://s4.anilist.co/file/anilistcdn/character/large/b4368-1KToX8uSi1U1.png",
"jojo:Jolyne Cujoh": "https://s4.anilist.co/file/anilistcdn/character/large/b11222-Se9QoJHDSeYY.png",
"jojo:Jonathan Joestar": "https://s4.anilist.co/file/anilistcdn/character/large/b8087-GTrObHQvujB5.png",
"jojo:Joseph Joestar": "https://s4.anilist.co/file/anilistcdn/character/large/b6356-RImEfUfHpC58.png",
"jojo:Josuke Higashikata": "https://s4.anilist.co/file/anilistcdn/character/large/b13085-CkmgXL7SSLxL.jpg",
"jojo:Jotaro Kujo": "https://s4.anilist.co/file/anilistcdn/character/large/b4003-gWDSEGbeOAll.png",
"jojo:Muhammad Avdol": "https://s4.anilist.co/file/anilistcdn/character/large/b8946-BumWgNGkPP9W.jpg",
"jojo:Noriaki Kakyoin": "https://s4.anilist.co/file/anilistcdn/character/large/8945-gyPfrVpCb5CF.jpg",
"jojo:Yoshikage Kira": "https://s4.anilist.co/file/anilistcdn/character/large/b12055-eCEkIVV4qoCu.png",
"kny:Akaza": "https://s4.anilist.co/file/anilistcdn/character/large/b141694-0COi0GVXPuEn.png",
"kny:Doma": "https://s4.anilist.co/file/anilistcdn/character/large/b144591-v2yrXtHorZFS.png",
"kny:Giyu Tomioka": "https://s4.anilist.co/file/anilistcdn/character/large/b130050-qsLThJs5VIbz.png",
"kny:Inosuke Hashibira": "https://s4.anilist.co/file/anilistcdn/character/large/n129130-SJC0Kn1DU39E.jpg",
"kny:Kanao Tsuyuri": "https://s4.anilist.co/file/anilistcdn/character/large/b139038-OcOoDUyLEsRn.png",
"kny:Kokushibo": "https://s4.anilist.co/file/anilistcdn/character/large/b141918-Bfgq88XJFOPz.png",
"kny:Kyojuro Rengoku": "https://s4.anilist.co/file/anilistcdn/character/large/b129133-VlTPowwt68rJ.png",
"kny:Mitsuri Kanroji": "https://s4.anilist.co/file/anilistcdn/character/large/b136072-xVwyRUKdpybi.png",
"kny:Muichiro Tokito": "https://s4.anilist.co/file/anilistcdn/character/large/b136069-6PLglx4tETUX.png",
"kny:Muzan Kibutsuji": "https://s4.anilist.co/file/anilistcdn/character/large/b129132-4nIZakUZ1o8W.jpg",
"kny:Nezuko Kamado": "https://s4.anilist.co/file/anilistcdn/character/large/b127518-NRlq1CQ1v1ro.png",
"kny:Sakonji Urokodaki": "https://s4.anilist.co/file/anilistcdn/character/large/b137773-N4O52f73dJKZ.png",
"kny:Sanemi Shinazugawa": "https://s4.anilist.co/file/anilistcdn/character/large/b137774-O1iYrnGLB71l.png",
"kny:Shinobu Kocho": "https://s4.anilist.co/file/anilistcdn/character/large/b136070-MC9LLxJsHyHE.png",
"kny:Tanjiro Kamado": "https://s4.anilist.co/file/anilistcdn/character/large/b126071-BTNEc1nRIv68.png",
"kny:Tengen Uzui": "https://s4.anilist.co/file/anilistcdn/character/large/b136071-99Kexnnn2PiV.png",
"kny:Zenitsu Agatsuma": "https://s4.anilist.co/file/anilistcdn/character/large/b129131-FZrQ7lSlxmEr.png",
"mha:All For One": "https://s4.anilist.co/file/anilistcdn/character/large/125956-jzhb8Z4peLb8.jpg",
"mha:All Might": "https://s4.anilist.co/file/anilistcdn/character/large/b89224-K6KEuQAuYKzq.jpg",
"mha:Dabi": "https://s4.anilist.co/file/anilistcdn/character/large/b126378-RFSljq5koy5U.png",
"mha:Denki Kaminari": "https://s4.anilist.co/file/anilistcdn/character/large/b89249-Ygc30RlYoFta.png",
"mha:Eijiro Kirishima": "https://s4.anilist.co/file/anilistcdn/character/large/b89243-R2WJlNuj3aEs.jpg",
"mha:Endeavor": "https://s4.anilist.co/file/anilistcdn/character/large/b126158-Wix9rh7unTDQ.png",
"mha:Hawks": "https://s4.anilist.co/file/anilistcdn/character/large/b128299-eMEsWazNXE56.png",
"mha:Himiko Toga": "https://s4.anilist.co/file/anilistcdn/character/large/b125619-iQxQoGHJvjRJ.png",
"mha:Izuku Midoriya": "https://s4.anilist.co/file/anilistcdn/character/large/b89028-8w1I9o1ISHMg.png",
"mha:Kai Chisaki": "https://s4.anilist.co/file/anilistcdn/character/large/126357-d5wTLYqKchRv.jpg",
"mha:Katsuki Bakugo": "https://s4.anilist.co/file/anilistcdn/character/large/b88892-bdOha3lNcaN6.png",
"mha:Momo Yaoyorozu": "https://s4.anilist.co/file/anilistcdn/character/large/b89241-Q8KzAfX4Qe2y.png",
"mha:Ochaco Uraraka": "https://s4.anilist.co/file/anilistcdn/character/large/b89221-gSF2a4gPbG4m.png",
"mha:Shota Aizawa": "https://s4.anilist.co/file/anilistcdn/character/large/b89225-XBgvUhI9naVI.png",
"mha:Shoto Todoroki": "https://s4.anilist.co/file/anilistcdn/character/large/b89220-KNBwaVFAR8FD.png",
"mha:Stain": "https://s4.anilist.co/file/anilistcdn/character/large/b126067-ZL6sRFyaqX9c.png",
"mha:Tenya Iida": "https://s4.anilist.co/file/anilistcdn/character/large/b89222-TL8MQM3wJgEB.png",
"mha:Tomura Shigaraki": "https://s4.anilist.co/file/anilistcdn/character/large/b89226-qGXqFthO4SM3.jpg",
"mha:Tsuyu Asui": "https://s4.anilist.co/file/anilistcdn/character/large/b89223-5762vburxnlz.png",
"mob:Arataka Reigen": "https://s4.anilist.co/file/anilistcdn/character/large/b89334-OPj1hCzvrt7X.png",
"mob:Dimple": "https://s4.anilist.co/file/anilistcdn/character/large/b89617-HHZ1kziYxc0q.png",
"mob:Ritsu Kageyama": "https://s4.anilist.co/file/anilistcdn/character/large/b89618-iSTUyCdu1yZ8.png",
"mob:Shigeo Kageyama": "https://s4.anilist.co/file/anilistcdn/character/large/b89616-dXmdOc7L6SDi.png",
"mob:Teru Hanazawa": "https://s4.anilist.co/file/anilistcdn/character/large/b89621-3uLnmhFOGYFv.png",
"naruto:Deidara": "https://s4.anilist.co/file/anilistcdn/character/large/b1902-JsEFRFwjmtZJ.png",
"naruto:Gaara": "https://s4.anilist.co/file/anilistcdn/character/large/b1662-4E5J0LX9jZKZ.png",
"naruto:Haku": "https://s4.anilist.co/file/anilistcdn/character/large/b2039-9NXBvh6H15LD.png",
"naruto:Hinata Hyuga": "https://s4.anilist.co/file/anilistcdn/character/large/b1555-Q41GLTV3FvYF.png",
"naruto:Hiruzen Sarutobi": "https://s4.anilist.co/file/anilistcdn/character/large/n7571-fKldLuBWUtCO.png",
"naruto:Iruka Umino": "https://s4.anilist.co/file/anilistcdn/character/large/b2011-WUBm7wMCA6cE.png",
"naruto:Itachi Uchiha": "https://s4.anilist.co/file/anilistcdn/character/large/b14-9Kb1E5oel1ke.png",
"naruto:Jiraiya": "https://s4.anilist.co/file/anilistcdn/character/large/b2423-RO5MyoXSA9OL.png",
"naruto:Kakashi Hatake": "https://s4.anilist.co/file/anilistcdn/character/large/b85-mkVBh2yjxjmx.png",
"naruto:Kisame Hoshigaki": "https://s4.anilist.co/file/anilistcdn/character/large/2672-oxbHx8n3N7WY.jpg",
"naruto:Kurama (Kyubi)": "https://s4.anilist.co/file/anilistcdn/character/large/b7407-D8MYzhbuy8zu.jpg",
"naruto:Madara Uchiha": "https://s4.anilist.co/file/anilistcdn/character/large/b53901-HnRKSoHMG5Vg.png",
"naruto:Might Guy": "https://s4.anilist.co/file/anilistcdn/character/large/b307-xieUEdhdTVwQ.png",
"naruto:Minato Namikaze": "https://s4.anilist.co/file/anilistcdn/character/large/b2535-Xq9WKNPJQEt3.png",
"naruto:Nagato": "https://s4.anilist.co/file/anilistcdn/character/large/b3180-ITMGBLWNBOgV.png",
"naruto:Naruto Uzumaki": "https://s4.anilist.co/file/anilistcdn/character/large/b17-phjcWCkRuIhu.png",
"naruto:Neji Hyuga": "https://s4.anilist.co/file/anilistcdn/character/large/b1694-TL4obouDwJ7k.jpg",
"naruto:Obito Uchiha": "https://s4.anilist.co/file/anilistcdn/character/large/b3149-j6cl8A9yup51.png",
"naruto:Orochimaru": "https://s4.anilist.co/file/anilistcdn/character/large/n2455-V9tLMS3TIgJW.png",
"naruto:Rock Lee": "https://s4.anilist.co/file/anilistcdn/character/large/b306-oUTOO45xInXt.png",
"naruto:Sakura Haruno": "https://s4.anilist.co/file/anilistcdn/character/large/b145-IorfpI8arxeX.png",
"naruto:Sasuke Uchiha": "https://s4.anilist.co/file/anilistcdn/character/large/b13-SISLEw1oAD7a.png",
"naruto:Shikamaru Nara": "https://s4.anilist.co/file/anilistcdn/character/large/b2007-QaesJlIZDifj.jpg",
"naruto:Tsunade": "https://s4.anilist.co/file/anilistcdn/character/large/b2767-r61Cj9v8I0wl.png",
"naruto:Zabuza Momochi": "https://s4.anilist.co/file/anilistcdn/character/large/b728-zHw77BzLzQKT.jpg",
"onepiece:Arlong": "https://s4.anilist.co/file/anilistcdn/character/large/b4887-hMOqSSpR5jFc.jpg",
"onepiece:Boa Hancock": "https://s4.anilist.co/file/anilistcdn/character/large/b16342-kVOF6V5Q94go.png",
"onepiece:Borsalino": "https://s4.anilist.co/file/anilistcdn/character/large/b21093-Pc4kOjUn3ZkZ.png",
"onepiece:Brook": "https://s4.anilist.co/file/anilistcdn/character/large/b5627-av8oD3zhKvDl.png",
"onepiece:Buggy": "https://s4.anilist.co/file/anilistcdn/character/large/n725-g04AaiaK5f9B.png",
"onepiece:Charlotte Linlin": "https://s4.anilist.co/file/anilistcdn/character/large/b54495-3x1TzSzPEOLd.jpg",
"onepiece:Crocodile": "https://s4.anilist.co/file/anilistcdn/character/large/b2749-e8ebEBN1SlS2.png",
"onepiece:Donquixote Doflamingo": "https://s4.anilist.co/file/anilistcdn/character/large/b2754-B4gGSlNYgsyh.jpg",
"onepiece:Dracule Mihawk": "https://s4.anilist.co/file/anilistcdn/character/large/n2064-OpnF4nLi6bvL.png",
"onepiece:Edward Newgate": "https://s4.anilist.co/file/anilistcdn/character/large/b2751-NnzW0N2vCTjX.jpg",
"onepiece:Franky": "https://s4.anilist.co/file/anilistcdn/character/large/n64-ChX6ZzHHjXqA.png",
"onepiece:Gol D. Roger": "https://s4.anilist.co/file/anilistcdn/character/large/b4883-0t76xH00sehO.png",
"onepiece:Jinbe": "https://s4.anilist.co/file/anilistcdn/character/large/b18938-yZANEfjsVhW4.png",
"onepiece:Kaido": "https://s4.anilist.co/file/anilistcdn/character/large/b46109-MT7Hm4Bk93In.png",
"onepiece:Marshall D. Teach": "https://s4.anilist.co/file/anilistcdn/character/large/b3331-7ZJDc4BNv9Yp.jpg",
"onepiece:Monkey D. Luffy": "https://s4.anilist.co/file/anilistcdn/character/large/b40-MNypXsxSRb1R.png",
"onepiece:Nami": "https://s4.anilist.co/file/anilistcdn/character/large/b723-vp5hPptgnNEC.png",
"onepiece:Nefertari Vivi": "https://s4.anilist.co/file/anilistcdn/character/large/b726-DqAIpscMuYYx.png",
"onepiece:Nico Robin": "https://s4.anilist.co/file/anilistcdn/character/large/b61-ywXUyyocEEqt.png",
"onepiece:Portgas D. Ace": "https://s4.anilist.co/file/anilistcdn/character/large/b2072-Lc6jEdsueJUK.jpg",
"onepiece:Rob Lucci": "https://s4.anilist.co/file/anilistcdn/character/large/b5677-ZrZunVe7Kq5P.png",
"onepiece:Roronoa Zoro": "https://s4.anilist.co/file/anilistcdn/character/large/b62-S7oAeA9WInjV.png",
"onepiece:Sabo": "https://s4.anilist.co/file/anilistcdn/character/large/b32893-3weZS61cdwLD.png",
"onepiece:Sanji": "https://s4.anilist.co/file/anilistcdn/character/large/b305-6lisPmHtCnLT.png",
"onepiece:Shanks": "https://s4.anilist.co/file/anilistcdn/character/large/b727-wUJx7M1z5xON.png",
"onepiece:Smoker": "https://s4.anilist.co/file/anilistcdn/character/large/b2753-Y2ja8Pl6PRs0.jpg",
"onepiece:Tony Tony Chopper": "https://s4.anilist.co/file/anilistcdn/character/large/b309-H64NhbJ2ywIQ.jpg",
"onepiece:Trafalgar Law": "https://s4.anilist.co/file/anilistcdn/character/large/b13767-U604OJN9dxCn.jpg",
"onepiece:Usopp": "https://s4.anilist.co/file/anilistcdn/character/large/b724-GFGgI9AJQkfy.jpg",
"opm:Atomic Samurai": "https://s4.anilist.co/file/anilistcdn/character/large/b154767-B8TieN81pfMI.png",
"opm:Bang": "https://s4.anilist.co/file/anilistcdn/character/large/n81141-1ml7Q6X2B508.png",
"opm:Boros": "https://s4.anilist.co/file/anilistcdn/character/large/n89263-GPItRQ64F27D.png",
"opm:Fubuki": "https://s4.anilist.co/file/anilistcdn/character/large/b81931-fmouMoprPVbV.png",
"opm:Garou": "https://s4.anilist.co/file/anilistcdn/character/large/b89277-xBGb4B5YISXg.png",
"opm:Genos": "https://s4.anilist.co/file/anilistcdn/character/large/b73979-tVi9maPID881.jpg",
"opm:Saitama": "https://s4.anilist.co/file/anilistcdn/character/large/b73935-ON5d0mAcrItd.jpg",
"opm:Speed of Sound Sonic": "https://s4.anilist.co/file/anilistcdn/character/large/b74167-FE8EtGtHUM77.png",
"opm:Tatsumaki": "https://s4.anilist.co/file/anilistcdn/character/large/b81929-WPVp2LQoWgkc.png",
"oshinoko:Ai Hoshino": "https://s4.anilist.co/file/anilistcdn/character/large/b172759-cccVhJ2fQA92.png",
"oshinoko:Akane Kurokawa": "https://s4.anilist.co/file/anilistcdn/character/large/b203384-YuSppFDMw2wn.png",
"oshinoko:Aqua Hoshino": "https://s4.anilist.co/file/anilistcdn/character/large/b183885-HOmw8CqcJdv3.jpg",
"oshinoko:Kana Arima": "https://s4.anilist.co/file/anilistcdn/character/large/b188783-77orwP7vNuNg.png",
"oshinoko:Ruby Hoshino": "https://s4.anilist.co/file/anilistcdn/character/large/b183884-iyo3BmTuhJ0l.jpg",
"pokemon:Ash Ketchum": "https://s4.anilist.co/file/anilistcdn/character/large/b2473-JDoo3I82Km4l.png",
"pokemon:Brock": "https://s4.anilist.co/file/anilistcdn/character/large/b3854-qMVUF2YmWYoW.png",
"pokemon:Gary Oak": "https://s4.anilist.co/file/anilistcdn/character/large/b4848-vR9au1dEKjyy.png",
"pokemon:James": "https://s4.anilist.co/file/anilistcdn/character/large/b3936-5sX4EZIY2BRU.png",
"pokemon:Jessie": "https://s4.anilist.co/file/anilistcdn/character/large/b3935-m000RuoIVOGI.png",
"pokemon:Meowth": "https://s4.anilist.co/file/anilistcdn/character/large/b3937-qBtTAn2SZqhB.png",
"pokemon:Misty": "https://s4.anilist.co/file/anilistcdn/character/large/b2909-wNDR5aaxwDdi.png",
"pokemon:Pikachu": "https://s4.anilist.co/file/anilistcdn/character/large/b3891-edgrZOgCJ9do.jpg",
"pokemon:Profesor Oak": "https://s4.anilist.co/file/anilistcdn/character/large/b17783-OwYJSOFjd91A.png",
"sailormoon:Ami Mizuno": "https://s4.anilist.co/file/anilistcdn/character/large/b2366-IJmfKZoSYT3N.png",
"sailormoon:Chibiusa": "https://s4.anilist.co/file/anilistcdn/character/large/b2827-XDpzQoIQSPL8.jpg",
"sailormoon:Luna": "https://s4.anilist.co/file/anilistcdn/character/large/5407.jpg",
"sailormoon:Makoto Kino": "https://s4.anilist.co/file/anilistcdn/character/large/b2825-d7HrsHjJgixD.png",
"sailormoon:Mamoru Chiba": "https://s4.anilist.co/file/anilistcdn/character/large/b4013-pnQ2obKyW7Tv.png",
"sailormoon:Minako Aino": "https://s4.anilist.co/file/anilistcdn/character/large/b2826-BwX3oCmxTo6A.png",
"sailormoon:Rei Hino": "https://s4.anilist.co/file/anilistcdn/character/large/b2367-KAExXjTB13mJ.png",
"sailormoon:Usagi Tsukino": "https://s4.anilist.co/file/anilistcdn/character/large/b2030-GQvVYPEYkXCy.jpg",
"sao:Asuna Yuuki": "https://s4.anilist.co/file/anilistcdn/character/large/b36828-j5ib0adAzGMx.png",
"sao:Heathcliff": "https://s4.anilist.co/file/anilistcdn/character/large/b36829-X5zITNEQ7xij.png",
"sao:Kirito": "https://s4.anilist.co/file/anilistcdn/character/large/b36765-BnLbXg0Tzzh9.png",
"sao:Klein": "https://s4.anilist.co/file/anilistcdn/character/large/b36830-41SWIDvhqOo4.png",
"sao:Leafa": "https://s4.anilist.co/file/anilistcdn/character/large/b36831-JfyFU7gPPVmr.png",
"sao:Sinon": "https://s4.anilist.co/file/anilistcdn/character/large/b55147-1fCU8lONEuZQ.png",
"sao:Yui": "https://s4.anilist.co/file/anilistcdn/character/large/b43892-Ig6ZMdUbQDO2.jpg",
"sololeveling:Beru": "https://s4.anilist.co/file/anilistcdn/character/large/b159849-p0Szb7KzD2DD.png",
"sololeveling:Cha Hae-In": "https://s4.anilist.co/file/anilistcdn/character/large/b138789-AhE8m0LWjE7E.png",
"sololeveling:Igris": "https://s4.anilist.co/file/anilistcdn/character/large/b145722-qSJ71S6vpeeM.png",
"sololeveling:Sung Jin-Woo": "https://s4.anilist.co/file/anilistcdn/character/large/b129928-BCEjVaP0AQSw.png",
"spyfam:Anya Forger": "https://s4.anilist.co/file/anilistcdn/character/large/b138100-4Li0tWRCa5bQ.png",
"spyfam:Becky Blackbell": "https://s4.anilist.co/file/anilistcdn/character/large/b150423-RxXwrHzeLCss.jpg",
"spyfam:Bond Forger": "https://s4.anilist.co/file/anilistcdn/character/large/b169679-EFPubVtZFYom.jpg",
"spyfam:Damian Desmond": "https://s4.anilist.co/file/anilistcdn/character/large/b150424-4B4psF6I4dgO.png",
"spyfam:Franky Franklin": "https://s4.anilist.co/file/anilistcdn/character/large/b157888-zkSfIT5Z8y2S.png",
"spyfam:Loid Forger": "https://s4.anilist.co/file/anilistcdn/character/large/b138101-7NCB0Md8zA6G.png",
"spyfam:Yor Forger": "https://s4.anilist.co/file/anilistcdn/character/large/b138102-ZOAu9jI2d5ke.png",
"spyfam:Yuri Briar": "https://s4.anilist.co/file/anilistcdn/character/large/b150425-mP852peLh9eS.jpg",
"tg:Hideyoshi Nagachika": "https://s4.anilist.co/file/anilistcdn/character/large/b88421-F8yaeVfHjwYn.png",
"tg:Juuzou Suzuya": "https://s4.anilist.co/file/anilistcdn/character/large/b88412-sIOJUnIkyFRe.png",
"tg:Ken Kaneki": "https://s4.anilist.co/file/anilistcdn/character/large/b87275-mb13EWZBdbh3.png",
"tg:Kisho Arima": "https://s4.anilist.co/file/anilistcdn/character/large/b88946-YbTQAGJAdpoH.jpg",
"tg:Rize Kamishiro": "https://s4.anilist.co/file/anilistcdn/character/large/b88413-FmAvV0hGSljG.png",
"tg:Shuu Tsukiyama": "https://s4.anilist.co/file/anilistcdn/character/large/b88424-mFPgcZlCuODC.png",
"tg:Touka Kirishima": "https://s4.anilist.co/file/anilistcdn/character/large/b87277-oUaqrI1iBzu6.png",
"tg:Yamori": "https://s4.anilist.co/file/anilistcdn/character/large/88428.jpg",
"tg:Yoshimura": "https://s4.anilist.co/file/anilistcdn/character/large/b136024-cSFppR7s21xh.png",
"yyh:Genkai": "https://s4.anilist.co/file/anilistcdn/character/large/b735-C85KgkJl660I.jpg",
"yyh:Hiei": "https://s4.anilist.co/file/anilistcdn/character/large/b732-rg4H7yyv3LRo.png",
"yyh:Kazuma Kuwabara": "https://s4.anilist.co/file/anilistcdn/character/large/n730-H6SRWfoiFjBR.jpg",
"yyh:Kurama (Yu Yu Hakusho)": "https://s4.anilist.co/file/anilistcdn/character/large/b731-cv0jfjVrD09V.jpg",
"yyh:Toguro": "https://s4.anilist.co/file/anilistcdn/character/large/7176.jpg",
"yyh:Yusuke Urameshi": "https://s4.anilist.co/file/anilistcdn/character/large/b729-V6GlADOEZv3x.png"
};
window.ANIME_IMAGES = {
"aot": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx16498-buvcRTBx4NSm.jpg",
"bc": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx97940-fyh8o7gNbha0.png",
"bebop": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx1-GCsPm7waJ4kS.png",
"bleach": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx269-d2GmRkJbMopq.png",
"bluelock": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx137822-U8naszP96vzC.png",
"cg": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx1575-hsmWM2ydNm1m.jpg",
"csm": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx127230-DdP4vAdssLoz.png",
"dandadan": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx171018-60q1B6GK2Ghb.jpg",
"deathnote": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx1535-kUgkcrfOrkUM.jpg",
"dragonball": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx813-ZhnFNOeCU5dQ.png",
"eva": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx30-AI1zr74Dh4ye.jpg",
"fma": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx5114-nSWCgQlmOMtj.jpg",
"frieren": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx154587-qQTzQnEJJ3oB.jpg",
"ft": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/b6702-KI4qgSMyI8Pm.png",
"haikyuu": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx20464-ooZUyBe4ptp9.png",
"hxh": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx11061-y5gsT1hoHuHw.png",
"jjk": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx113415-LHBAeoZDIsnF.jpg",
"jojo": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx14719-VT5dRzTBSZ0w.jpg",
"kny": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx101922-WBsBl0ClmgYL.jpg",
"mha": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx21459-nYh85uj2Fuwr.jpg",
"mob": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx21507-6YUSbh2m0N1p.jpg",
"naruto": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx20-dE6UHbFFg1A5.jpg",
"onepiece": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx21-ELSYx3yMPcKM.jpg",
"opm": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx21087-B5DHjqZ3kW4b.jpg",
"oshinoko": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx150672-WqmmwZ4nMzAy.png",
"pokemon": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/b527-t6dBVJ5OVcXK.png",
"sailormoon": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx530-O8q6KpJ244Qk.jpg",
"sao": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx11757-SxYDUzdr9rh2.jpg",
"sololeveling": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx151807-it355ZgzquUd.png",
"spyfam": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx140960-Kb6R5nYQfjmP.jpg",
"tg": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/b20605-k665mVkSug8D.jpg",
"yyh": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx392-z90299zIvYmx.png"
};
